spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  liquibase:
    enabled: false
    change-log: db/changelog/db.changelog.xml
    drop-first: true

server:
  port: 8088
  error:
    whitelabel:
      enabled: false
